schemaPath: src/graphql/schema.graphql
extensions:
  codegen:
    generator: graphql-binding
    language: typescript
    input:
      schema: src/graphql/schema.ts
    output:
      binding: src/generated/binding.ts
