schemaPath: src/graphql/schema.graphql
extensions:
  endpoints:
    default: "http://localhost:4000"
  prepare-bundle: src/generated/schema.graphql
  codegen:
    generator: graphql-binding
    language: typescript
    input:
      schema: src/schema.ts
    output:
      binding: src/generated/schema.ts
