projects:
  themoviedb:
    schemaPath: src/generated/schema.graphql
    extensions:
      # prepare-bundle: src/generated/schema.graphql
      endpoints:
        dev: "http://localhost:4000"
        prod: "http://themoviedb-graphql.now.sh"
      codegen:
        generator: graphql-binding
        language: typescript
        input:
          schema: src/generated/schema.graphql
        output:
          binding: src/generated/schema.ts
